<?php



$testXML =

'<?xml version="1.0" encoding="iso-8859-1" ?>
<XML Type="ListBuilder">
	<Order No="2011000175" DispDate="07.04.2011" Basket="175">
		<Head>
			<COMM>centraljoinery 07.04.2011 22:41:22</COMM>
			<ARTICLENO>2011000175</ARTICLENO>
			<CUSTOMER></CUSTOMER>
			<RETAILER></RETAILER>
			<CLIENT></CLIENT>
			<PROGRAM></PROGRAM>
			<EMPLOYEE></EMPLOYEE>
			<TEXT_LONG></TEXT_LONG>
			<TEXT_SHORT></TEXT_SHORT>

			<COLOUR1></COLOUR1>
			<COLOUR2></COLOUR2>
			<COLOUR3></COLOUR3>
			<COLOUR4></COLOUR4>
			<COLOUR5></COLOUR5>

			<INFO1>Brownpaperbag</INFO1>
			<INFO2></INFO2>
			<INFO3>4 Cavendish Drive</INFO3>
			<INFO4>2104</INFO4>
			<INFO5>Manukau</INFO5>
			<INFO6>KNR08/16</INFO6>
			<INFO7></INFO7>
			<INFO8></INFO8>
			<INFO9></INFO9>
		   <INFO10></INFO10>
                    
			<ADDRESS1></ADDRESS1>
			<ADDRESS2></ADDRESS2>
			<ADDRESS3></ADDRESS3>
			<ADDRESS4></ADDRESS4>
			<ADDRESS5></ADDRESS5>
			<ADDRESS6></ADDRESS6>

			<BILLING_ADDRESS1></BILLING_ADDRESS1>
			<BILLING_ADDRESS2></BILLING_ADDRESS2>
			<BILLING_ADDRESS3></BILLING_ADDRESS3>
			<BILLING_ADDRESS4></BILLING_ADDRESS4>
			<BILLING_ADDRESS5></BILLING_ADDRESS5>
			<BILLING_ADDRESS6></BILLING_ADDRESS6>

			<SHIPPING_ADDRESS1></SHIPPING_ADDRESS1>
			<SHIPPING_ADDRESS2></SHIPPING_ADDRESS2>
			<SHIPPING_ADDRESS3></SHIPPING_ADDRESS3>
			<SHIPPING_ADDRESS4></SHIPPING_ADDRESS4>
			<SHIPPING_ADDRESS5></SHIPPING_ADDRESS5>
			<SHIPPING_ADDRESS6></SHIPPING_ADDRESS6>

			<ORDER_PRICE_INFO1>1785.190000</ORDER_PRICE_INFO1>
			<ORDER_PRICE_INFO2></ORDER_PRICE_INFO2>
			<ORDER_PRICE_INFO3></ORDER_PRICE_INFO3>
			<ORDER_PRICE_INFO4></ORDER_PRICE_INFO4>
			<ORDER_PRICE_INFO5></ORDER_PRICE_INFO5>

			<CUSTOM_INFO1>Brownpaperbag</CUSTOM_INFO1>
			<CUSTOM_INFO2></CUSTOM_INFO2>
			<CUSTOM_INFO3>2|29 Pitt Street</CUSTOM_INFO3>
			<CUSTOM_INFO4>1010</CUSTOM_INFO4>
			<CUSTOM_INFO5>Auckland</CUSTOM_INFO5>
			<CUSTOM_INFO6>KNR08/16</CUSTOM_INFO6>
			<CUSTOM_INFO7></CUSTOM_INFO7>
			<CUSTOM_INFO8></CUSTOM_INFO8>
			<CUSTOM_INFO9></CUSTOM_INFO9>
		   <CUSTOM_INFO10></CUSTOM_INFO10>

		</Head>
		<BuilderList>
			
			<Set LineNo="1">
				<Pname>B2D</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=971.5|ART_SIZEY:=560|ART_SIZEZ:=900|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA|BENCHTOP_MATERIAL:=SNOW|HANDLE_TYPE_SELECTION:=Pull_0115169|HANDLE_ROTATION:=0|HP_BU_HOR:=40mm|HP_BU_VER:=60mm|AS_AMOUNT:=1:1</PVarString>
				<ARTICLE_TEXT_INFO1>B2D</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4>test</ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>339.61</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>339.61</ARTICLE_PRICE_INFO2>
				<PInsertion>5780.00,5000.00,0.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			

			<Set LineNo="2">
				<Pname>B2D</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=971.5|ART_SIZEY:=560|ART_SIZEZ:=900|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA|BENCHTOP_MATERIAL:=SNOW|HANDLE_TYPE_SELECTION:=Pull_0115169|HANDLE_ROTATION:=0|HP_BU_HOR:=40mm|HP_BU_VER:=60mm|AS_AMOUNT:=1:1</PVarString>
				<ARTICLE_TEXT_INFO1>B2D</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4></ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>339.61</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>339.61</ARTICLE_PRICE_INFO2>
				<PInsertion>4810.00,5000.00,0.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			

			<Set LineNo="3">
				<Pname>BEF</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=18|ART_SIZEY_FAKE:=100|ART_SIZEY:=560|ART_SIZEZ:=900|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA|BENCHTOP_MATERIAL:=SNOW</PVarString>
				<ARTICLE_TEXT_INFO1>BEF</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4></ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>125.54</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>125.54</ARTICLE_PRICE_INFO2>
				<PInsertion>6750.00,5000.00,0.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			

			<Set LineNo="4">
				<Pname>BEP</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=18|ART_SIZEY_FAKE:=580|ART_SIZEY:=560|ART_SIZEZ:=900|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA|BENCHTOP_MATERIAL:=SNOW</PVarString>
				<ARTICLE_TEXT_INFO1>BEP</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4></ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>147.29</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>147.29</ARTICLE_PRICE_INFO2>
				<PInsertion>4790.00,5000.00,0.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			

			<Set LineNo="5">
				<Pname>W2D</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=971.5|ART_SIZEY:=330|ART_SIZEZ:=600|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA|HANDLE_TYPE_SELECTION:=Pull_0115169|HANDLE_ROTATION:=0|HP_BU_HOR:=40mm|HP_BU_VER:=60mm|DOOR_STYLE:=Plain_Door|FRAME_DOOR_SWITCH:=PLAIN_DOOR_HINGE|AS_AMOUNT:=1:1</PVarString>
				<ARTICLE_TEXT_INFO1>W2D</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4></ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>286.22</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>286.22</ARTICLE_PRICE_INFO2>
				<PInsertion>5800.00,5000.00,1600.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			

			<Set LineNo="6">
				<Pname>W2D</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=971.5|ART_SIZEY:=330|ART_SIZEZ:=600|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA|HANDLE_TYPE_SELECTION:=Pull_0115169|HANDLE_ROTATION:=0|HP_BU_HOR:=40mm|HP_BU_VER:=60mm|DOOR_STYLE:=Plain_Door|FRAME_DOOR_SWITCH:=PLAIN_DOOR_HINGE|AS_AMOUNT:=1:1</PVarString>
				<ARTICLE_TEXT_INFO1>W2D</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4></ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>286.22</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>286.22</ARTICLE_PRICE_INFO2>
				<PInsertion>4830.00,5000.00,1600.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			

			<Set LineNo="7">
				<Pname>WEP</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=18|ART_SIZEY_FAKE:=350|ART_SIZEY:=330|ART_SIZEZ:=600|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA</PVarString>
				<ARTICLE_TEXT_INFO1>WEP</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4></ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>130.35</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>130.35</ARTICLE_PRICE_INFO2>
				<PInsertion>6770.00,5000.00,1600.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			

			<Set LineNo="8">
				<Pname>WEP</Pname>
				<Count>1</Count>
				<PVarString>ART_BUILDFLAGS:=15238|ART_SIZEX:=18|ART_SIZEY_FAKE:=350|ART_SIZEY:=330|ART_SIZEZ:=600|FRONT_MATERIAL_AND_EDGE:=SILVER_STRATA</PVarString>
				<ARTICLE_TEXT_INFO1>WEP</ARTICLE_TEXT_INFO1>
				<ARTICLE_TEXT_INFO2></ARTICLE_TEXT_INFO2>
				<ARTICLE_TEXT_INFO3></ARTICLE_TEXT_INFO3>
				<ARTICLE_TEXT_INFO4></ARTICLE_TEXT_INFO4>
				<ARTICLE_PRICE_INFO1>130.35</ARTICLE_PRICE_INFO1>
				<ARTICLE_PRICE_INFO2>130.35</ARTICLE_PRICE_INFO2>
				<PInsertion>4810.00,5000.00,1600.00</PInsertion>
				<POrntation>0.00,0.00,0.00</POrntation>
				<!--
				<ArticleNumber>0</ArticleNumber>
				-->
			</Set>
			
		</BuilderList>
	</Order>
</XML>';

$ch = curl_init();

curl_setopt( $ch, CURLOPT_URL, 'http://onlinekitchens.ongoing.co.nz/checkout' );

//curl_setopt( $ch, CURLOPT_URL, 'http://localhost/onlinekitchens/checkout' );

curl_setopt( $ch, CURLOPT_POST, true );

curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );

curl_setopt( $ch, CURLOPT_POSTFIELDS, $testXML );

$raw_response = curl_exec( $ch );

session_start();

$_SESSION['basketid'] = $raw_response; 
header("location: checkout_1?id=" . $_SESSION['basketid']);
die();


print '<pre>';

var_dump( $raw_response );

print '</pre>';

